### ISSUE TITLE
Create a bundle to handle all your JS dependencies

### ISSUE THREAD

**Issue by Paul-Guerra** [markfguerra/node-socketio-chat#3]
Take the code found in https://github.com/markfguerra/node-socketio-chat/blob/master/webclient/index.html and use webpack to build a single app bundle with all relevant JS dependencies included.

You know you're done when there is only a single script tag required for the page to work

- [ ] create an "app bundle"
- [ ] Use NPM script to kick off the bundle build
- [ ] Have the bundle rebuilt every time you save a JS file

**Comment by markfguerra** [comment]
Sounds good. I'm on it.

**Comment by markfguerra** [comment]
@Paul-Guerra I've done some work on this. Let me know what you think and if you agree with these methodologies we can close this issue.

My efforts are shown in the commit range 2d0f765...4c50d95.
`git log 2d0f765...4c50d95`

In summary, our application's client side JS now comes in through the webpack bundle.
I also bundled in our CSS styles at commit dadb044.
Webpack can be run by the command `webpack` which will read the settings from webpack.config.js 68dceb0
There is now an NPM script webpack:watch which will recompile the bundle whenever there is a change to the files it is composed of. `npm run-script webpack:watch` 81cd9a5


Code smell warning:

1. The Bootstrap styles are still excluded from the bundle, for now.

2. bundle.js generates into /webclient, which is the source folder that express is serving content from. Because it is a generated file, it should not be committed to git. Instead of making a .gitignore entry for this one file (and then again later, for many one-off generated files), it is probably more prudent to move all our generated files to a new /dist folder, and .gitignore that folder. I created issue #5 to track that.

**Comment by Paul-Guerra** [comment]
Hey @markfguerra. I'm going to sit down and go through this now. How about in the future, we use the Pull Requests to review the changes that come from the issues. They will allow inline comments and a nice was of bundling the changes together for review. I can also then modify the branch you used in case I need to change something

**Comment by Paul-Guerra** [comment]
👍

**Comment by markfguerra** [comment]
@Paul-Guerra Sure, the review we did last time was good fun. Let's do more of that going forward.
